export const features = [
  {
    key: 'cases',
    title: 'Case Management',
    apiEndpoint: '/cases',
    icon: 'Briefcase',
    description: 'Manage litigation cases and matters',
    color: 'blue',
    group: 'CORE',
    columns: [
      { key: 'case_name', label: 'Case Name' },
      { key: 'case_number', label: 'Case #' },
      { key: 'client_name', label: 'Client' },
      { key: 'matter_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'priority', label: 'Priority' },
    ],
    formFields: [
      { key: 'case_name', label: 'Case Name', type: 'text', required: true },
      { key: 'case_number', label: 'Case Number', type: 'text', required: true },
      { key: 'client_name', label: 'Client Name', type: 'text', required: true },
      { key: 'matter_type', label: 'Matter Type', type: 'select', options: ['litigation', 'investigation', 'regulatory', 'compliance'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'pending', 'closed', 'archived'] },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'lead_attorney', label: 'Lead Attorney', type: 'text' },
      { key: 'date_filed', label: 'Date Filed', type: 'date' },
      { key: 'court_jurisdiction', label: 'Court/Jurisdiction', type: 'text' },
      { key: 'opposing_counsel', label: 'Opposing Counsel', type: 'text' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['high', 'medium', 'low'] },
    ],
  },
  {
    key: 'documents',
    title: 'Document Review',
    apiEndpoint: '/documents',
    icon: 'FileText',
    description: 'Review and classify case documents',
    color: 'indigo',
    group: 'CORE',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'file_type', label: 'Type' },
      { key: 'custodian', label: 'Custodian' },
      { key: 'review_status', label: 'Review Status' },
      { key: 'bates_number', label: 'Bates #' },
      { key: 'date_collected', label: 'Collected' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'file_type', label: 'File Type', type: 'select', options: ['pdf', 'docx', 'xlsx', 'eml', 'pptx', 'txt', 'csv', 'html'] },
      { key: 'file_size_mb', label: 'File Size (MB)', type: 'number' },
      { key: 'custodian', label: 'Custodian', type: 'text' },
      { key: 'source', label: 'Source', type: 'text' },
      { key: 'review_status', label: 'Review Status', type: 'select', options: ['pending', 'relevant', 'not_relevant', 'privileged', 'hot'] },
      { key: 'content_preview', label: 'Content Preview', type: 'textarea' },
      { key: 'date_collected', label: 'Date Collected', type: 'date' },
      { key: 'bates_number', label: 'Bates Number', type: 'text' },
      { key: 'hash_value', label: 'Hash Value', type: 'text' },
    ],
  },
  {
    key: 'legal-holds',
    title: 'Legal Holds',
    apiEndpoint: '/legal-holds',
    icon: 'Shield',
    description: 'Manage preservation and legal hold notices',
    color: 'red',
    group: 'MANAGEMENT',
    columns: [
      { key: 'hold_name', label: 'Hold Name' },
      { key: 'hold_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'custodian_count', label: 'Custodians' },
      { key: 'issued_date', label: 'Issued Date' },
      { key: 'notification_sent', label: 'Notified' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'hold_name', label: 'Hold Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'released', 'pending', 'expired'] },
      { key: 'custodian_count', label: 'Custodian Count', type: 'number' },
      { key: 'issued_by', label: 'Issued By', type: 'text' },
      { key: 'issued_date', label: 'Issued Date', type: 'date' },
      { key: 'release_date', label: 'Release Date', type: 'date' },
      { key: 'hold_type', label: 'Hold Type', type: 'select', options: ['litigation', 'regulatory', 'investigation'] },
      { key: 'notification_sent', label: 'Notification Sent', type: 'select', options: ['true', 'false'] },
    ],
  },
  {
    key: 'custodians',
    title: 'Custodian Management',
    apiEndpoint: '/custodians',
    icon: 'Users',
    description: 'Manage data custodians and their obligations',
    color: 'green',
    group: 'MANAGEMENT',
    columns: [
      { key: 'full_name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'department', label: 'Department' },
      { key: 'company', label: 'Company' },
      { key: 'status', label: 'Status' },
      { key: 'hold_status', label: 'Hold Status' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'full_name', label: 'Full Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'department', label: 'Department', type: 'text' },
      { key: 'title', label: 'Job Title', type: 'text' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'terminated'] },
      { key: 'data_sources', label: 'Data Sources', type: 'textarea' },
      { key: 'hold_status', label: 'Hold Status', type: 'select', options: ['on_hold', 'released', 'pending'] },
      { key: 'interview_date', label: 'Interview Date', type: 'date' },
    ],
  },
  {
    key: 'collections',
    title: 'Collections',
    apiEndpoint: '/collections',
    icon: 'FolderOpen',
    description: 'Manage data collection activities',
    color: 'yellow',
    group: 'MANAGEMENT',
    columns: [
      { key: 'collection_name', label: 'Collection Name' },
      { key: 'source_type', label: 'Source Type' },
      { key: 'custodian', label: 'Custodian' },
      { key: 'status', label: 'Status' },
      { key: 'total_items', label: 'Items' },
      { key: 'collection_date', label: 'Collected' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'collection_name', label: 'Collection Name', type: 'text', required: true },
      { key: 'source_type', label: 'Source Type', type: 'select', options: ['email', 'file_share', 'cloud', 'database', 'mobile', 'chat'] },
      { key: 'custodian', label: 'Custodian', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed', 'failed'] },
      { key: 'total_items', label: 'Total Items', type: 'number' },
      { key: 'total_size_gb', label: 'Total Size (GB)', type: 'number' },
      { key: 'collected_by', label: 'Collected By', type: 'text' },
      { key: 'collection_date', label: 'Collection Date', type: 'date' },
      { key: 'verification_status', label: 'Verification Status', type: 'text' },
    ],
  },
  {
    key: 'processing-jobs',
    title: 'Processing Jobs',
    apiEndpoint: '/processing-jobs',
    icon: 'Cpu',
    description: 'Track document processing and deduplication',
    color: 'orange',
    group: 'PROCESSING',
    columns: [
      { key: 'job_name', label: 'Job Name' },
      { key: 'processing_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'total_documents', label: 'Total Docs' },
      { key: 'processed_count', label: 'Processed' },
      { key: 'error_count', label: 'Errors' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'job_name', label: 'Job Name', type: 'text', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['queued', 'processing', 'completed', 'failed', 'paused'] },
      { key: 'total_documents', label: 'Total Documents', type: 'number' },
      { key: 'processed_count', label: 'Processed Count', type: 'number' },
      { key: 'duplicate_count', label: 'Duplicate Count', type: 'number' },
      { key: 'error_count', label: 'Error Count', type: 'number' },
      { key: 'processing_type', label: 'Processing Type', type: 'select', options: ['dedup', 'ocr', 'extraction', 'normalization'] },
    ],
  },
  {
    key: 'review-sets',
    title: 'Review Sets',
    apiEndpoint: '/review-sets',
    icon: 'Eye',
    description: 'Organize documents for review workflows',
    color: 'purple',
    group: 'PROCESSING',
    columns: [
      { key: 'set_name', label: 'Review Set' },
      { key: 'reviewer', label: 'Reviewer' },
      { key: 'status', label: 'Status' },
      { key: 'total_documents', label: 'Total' },
      { key: 'reviewed_count', label: 'Reviewed' },
      { key: 'priority', label: 'Priority' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'set_name', label: 'Set Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'total_documents', label: 'Total Documents', type: 'number' },
      { key: 'reviewed_count', label: 'Reviewed Count', type: 'number' },
      { key: 'relevant_count', label: 'Relevant Count', type: 'number' },
      { key: 'privileged_count', label: 'Privileged Count', type: 'number' },
      { key: 'reviewer', label: 'Reviewer', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'completed', 'paused'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['high', 'medium', 'low'] },
    ],
  },
  {
    key: 'productions',
    title: 'Productions',
    apiEndpoint: '/productions',
    icon: 'Package',
    description: 'Manage document production sets',
    color: 'teal',
    group: 'PROCESSING',
    columns: [
      { key: 'production_name', label: 'Production Name' },
      { key: 'bates_prefix', label: 'Bates Prefix' },
      { key: 'status', label: 'Status' },
      { key: 'format', label: 'Format' },
      { key: 'total_documents', label: 'Documents' },
      { key: 'confidentiality_level', label: 'Confidentiality' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'production_name', label: 'Production Name', type: 'text', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed', 'delivered'] },
      { key: 'format', label: 'Format', type: 'select', options: ['native', 'tiff', 'pdf'] },
      { key: 'total_documents', label: 'Total Documents', type: 'number' },
      { key: 'bates_prefix', label: 'Bates Prefix', type: 'text' },
      { key: 'bates_start', label: 'Bates Start', type: 'number' },
      { key: 'bates_end', label: 'Bates End', type: 'number' },
      { key: 'recipient', label: 'Recipient', type: 'text' },
      { key: 'delivery_date', label: 'Delivery Date', type: 'date' },
      { key: 'confidentiality_level', label: 'Confidentiality', type: 'select', options: ['confidential', 'highly_confidential', 'attorneys_eyes_only', 'public'] },
    ],
  },
  {
    key: 'search-queries',
    title: 'Search & Analytics',
    apiEndpoint: '/search-queries',
    icon: 'Search',
    description: 'Run and manage document search queries',
    color: 'cyan',
    group: 'ANALYSIS',
    columns: [
      { key: 'query_name', label: 'Query Name' },
      { key: 'query_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'results_count', label: 'Results' },
      { key: 'created_by', label: 'Created By' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'query_name', label: 'Query Name', type: 'text', required: true },
      { key: 'search_terms', label: 'Search Terms', type: 'textarea', required: true },
      { key: 'query_type', label: 'Query Type', type: 'select', options: ['keyword', 'boolean', 'concept', 'regex', 'proximity'] },
      { key: 'results_count', label: 'Results Count', type: 'number' },
      { key: 'created_by', label: 'Created By', type: 'text' },
      { key: 'date_range_start', label: 'Date Range Start', type: 'date' },
      { key: 'date_range_end', label: 'Date Range End', type: 'date' },
      { key: 'file_types_filter', label: 'File Types Filter', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['saved', 'executed', 'archived'] },
    ],
  },
  {
    key: 'predictive-coding',
    title: 'Predictive Coding',
    apiEndpoint: '/predictive-coding',
    icon: 'Brain',
    description: 'AI-powered document classification models',
    color: 'pink',
    group: 'ANALYSIS',
    columns: [
      { key: 'model_name', label: 'Model Name' },
      { key: 'algorithm', label: 'Algorithm' },
      { key: 'status', label: 'Status' },
      { key: 'accuracy', label: 'Accuracy' },
      { key: 'coded_docs', label: 'Coded Docs' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'model_name', label: 'Model Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['training', 'active', 'completed', 'archived'] },
      { key: 'accuracy', label: 'Accuracy', type: 'number' },
      { key: 'precision_score', label: 'Precision', type: 'number' },
      { key: 'recall_score', label: 'Recall', type: 'number' },
      { key: 'f1_score', label: 'F1 Score', type: 'number' },
      { key: 'training_docs', label: 'Training Docs', type: 'number' },
      { key: 'coded_docs', label: 'Coded Docs', type: 'number' },
      { key: 'algorithm', label: 'Algorithm', type: 'select', options: ['logistic_regression', 'svm', 'random_forest', 'neural_network', 'transformer'] },
    ],
  },
  {
    key: 'key-terms',
    title: 'Key Terms Analysis',
    apiEndpoint: '/key-terms',
    icon: 'Hash',
    description: 'Analyze key search terms and patterns',
    color: 'lime',
    group: 'ANALYSIS',
    columns: [
      { key: 'term', label: 'Term' },
      { key: 'category', label: 'Category' },
      { key: 'frequency', label: 'Frequency' },
      { key: 'relevance_score', label: 'Relevance' },
      { key: 'document_count', label: 'Documents' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'term', label: 'Term', type: 'text', required: true },
      { key: 'frequency', label: 'Frequency', type: 'number' },
      { key: 'relevance_score', label: 'Relevance Score', type: 'number' },
      { key: 'category', label: 'Category', type: 'select', options: ['person', 'organization', 'location', 'date', 'concept', 'financial'] },
      { key: 'context_snippet', label: 'Context Snippet', type: 'textarea' },
      { key: 'first_occurrence', label: 'First Occurrence', type: 'date' },
      { key: 'last_occurrence', label: 'Last Occurrence', type: 'date' },
      { key: 'document_count', label: 'Document Count', type: 'number' },
    ],
  },
  {
    key: 'timeline-events',
    title: 'Timeline Analysis',
    apiEndpoint: '/timeline-events',
    icon: 'Clock',
    description: 'Build and analyze case timelines',
    color: 'amber',
    group: 'INTELLIGENCE',
    columns: [
      { key: 'event_title', label: 'Event' },
      { key: 'event_date', label: 'Date' },
      { key: 'category', label: 'Category' },
      { key: 'significance', label: 'Significance' },
      { key: 'ai_generated', label: 'AI Generated' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'event_title', label: 'Event Title', type: 'text', required: true },
      { key: 'event_date', label: 'Event Date', type: 'date', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'category', label: 'Category', type: 'select', options: ['communication', 'filing', 'meeting', 'transaction', 'incident', 'discovery'] },
      { key: 'source_document', label: 'Source Document', type: 'text' },
      { key: 'participants', label: 'Participants', type: 'textarea' },
      { key: 'significance', label: 'Significance', type: 'select', options: ['high', 'medium', 'low'] },
      { key: 'ai_generated', label: 'AI Generated', type: 'select', options: ['true', 'false'] },
    ],
  },
  {
    key: 'email-threads',
    title: 'Email Threading',
    apiEndpoint: '/email-threads',
    icon: 'Mail',
    description: 'Analyze and organize email conversations',
    color: 'sky',
    group: 'INTELLIGENCE',
    columns: [
      { key: 'thread_subject', label: 'Subject' },
      { key: 'participant_count', label: 'Participants' },
      { key: 'message_count', label: 'Messages' },
      { key: 'sentiment', label: 'Sentiment' },
      { key: 'relevance_score', label: 'Relevance' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'thread_subject', label: 'Thread Subject', type: 'text', required: true },
      { key: 'participant_count', label: 'Participant Count', type: 'number' },
      { key: 'message_count', label: 'Message Count', type: 'number' },
      { key: 'date_range', label: 'Date Range', type: 'text' },
      { key: 'key_participants', label: 'Key Participants', type: 'textarea' },
      { key: 'has_attachments', label: 'Has Attachments', type: 'select', options: ['true', 'false'] },
      { key: 'sentiment', label: 'Sentiment', type: 'text' },
      { key: 'relevance_score', label: 'Relevance Score', type: 'number' },
      { key: 'thread_summary', label: 'Thread Summary', type: 'textarea' },
    ],
  },
  {
    key: 'anomaly-alerts',
    title: 'Anomaly Detection',
    apiEndpoint: '/anomaly-alerts',
    icon: 'AlertTriangle',
    description: 'Monitor and investigate data anomalies',
    color: 'rose',
    group: 'INTELLIGENCE',
    columns: [
      { key: 'alert_title', label: 'Alert' },
      { key: 'severity', label: 'Severity' },
      { key: 'alert_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'detected_date', label: 'Detected' },
      { key: 'ai_confidence', label: 'Confidence' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'alert_title', label: 'Alert Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'severity', label: 'Severity', type: 'select', options: ['critical', 'high', 'medium', 'low'] },
      { key: 'alert_type', label: 'Alert Type', type: 'select', options: ['data_gap', 'spike', 'pattern', 'unusual_access', 'deletion'] },
      { key: 'detected_date', label: 'Detected Date', type: 'date' },
      { key: 'affected_custodian', label: 'Affected Custodian', type: 'text' },
      { key: 'affected_date_range', label: 'Affected Date Range', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['new', 'investigating', 'resolved', 'dismissed'] },
      { key: 'ai_confidence', label: 'AI Confidence', type: 'number' },
    ],
  },
  {
    key: 'privilege-logs',
    title: 'Privilege Review',
    apiEndpoint: '/privilege-logs',
    icon: 'Lock',
    description: 'Track attorney-client privilege claims',
    color: 'violet',
    group: 'COMPLIANCE',
    columns: [
      { key: 'document_title', label: 'Document' },
      { key: 'bates_number', label: 'Bates #' },
      { key: 'privilege_type', label: 'Privilege Type' },
      { key: 'status', label: 'Status' },
      { key: 'reviewer', label: 'Reviewer' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'document_title', label: 'Document Title', type: 'text', required: true },
      { key: 'bates_number', label: 'Bates Number', type: 'text' },
      { key: 'privilege_type', label: 'Privilege Type', type: 'select', options: ['attorney_client', 'work_product', 'joint_defense', 'common_interest'] },
      { key: 'basis', label: 'Basis', type: 'textarea' },
      { key: 'author', label: 'Author', type: 'text' },
      { key: 'recipients', label: 'Recipients', type: 'textarea' },
      { key: 'date_of_communication', label: 'Date of Communication', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['logged', 'challenged', 'upheld', 'waived'] },
      { key: 'reviewer', label: 'Reviewer', type: 'text' },
    ],
  },
  {
    key: 'compliance-rules',
    title: 'Compliance Monitoring',
    apiEndpoint: '/compliance-rules',
    icon: 'CheckSquare',
    description: 'Define and enforce compliance policies',
    color: 'emerald',
    group: 'COMPLIANCE',
    columns: [
      { key: 'rule_name', label: 'Rule Name' },
      { key: 'regulation', label: 'Regulation' },
      { key: 'severity', label: 'Severity' },
      { key: 'status', label: 'Status' },
      { key: 'violations_count', label: 'Violations' },
      { key: 'automated', label: 'Automated' },
    ],
    formFields: [
      { key: 'rule_name', label: 'Rule Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'regulation', label: 'Regulation', type: 'select', options: ['gdpr', 'hipaa', 'sox', 'fcpa', 'ccpa', 'sec', 'frcp'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'under_review'] },
      { key: 'violations_count', label: 'Violations Count', type: 'number' },
      { key: 'affected_cases', label: 'Affected Cases', type: 'number' },
      { key: 'severity', label: 'Severity', type: 'select', options: ['critical', 'high', 'medium', 'low'] },
      { key: 'automated', label: 'Automated', type: 'select', options: ['true', 'false'] },
      { key: 'remediation_steps', label: 'Remediation Steps', type: 'textarea' },
    ],
  },
  {
    key: 'data-sources',
    title: 'Data Sources',
    apiEndpoint: '/data-sources',
    icon: 'Database',
    description: 'Manage connected data repositories',
    color: 'slate',
    group: 'COMPLIANCE',
    columns: [
      { key: 'source_name', label: 'Source Name' },
      { key: 'source_type', label: 'Type' },
      { key: 'connection_status', label: 'Connection' },
      { key: 'total_items', label: 'Items' },
      { key: 'last_synced', label: 'Last Synced' },
      { key: 'collection_priority', label: 'Priority' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'source_name', label: 'Source Name', type: 'text', required: true },
      { key: 'source_type', label: 'Source Type', type: 'select', options: ['exchange', 'sharepoint', 'onedrive', 'slack', 'teams', 'salesforce', 'box', 'google_workspace', 'local_server'] },
      { key: 'connection_status', label: 'Connection Status', type: 'select', options: ['connected', 'disconnected', 'error', 'pending'] },
      { key: 'custodian', label: 'Custodian', type: 'text' },
      { key: 'total_items', label: 'Total Items', type: 'number' },
      { key: 'total_size_gb', label: 'Total Size (GB)', type: 'number' },
      { key: 'credentials_stored', label: 'Credentials Stored', type: 'select', options: ['true', 'false'] },
      { key: 'collection_priority', label: 'Collection Priority', type: 'select', options: ['high', 'medium', 'low'] },
    ],
  },
];

export const featureGroups = {
  CORE: { label: 'Core', color: 'blue' },
  MANAGEMENT: { label: 'Management', color: 'green' },
  PROCESSING: { label: 'Processing', color: 'orange' },
  ANALYSIS: { label: 'Analysis', color: 'cyan' },
  INTELLIGENCE: { label: 'Intelligence', color: 'amber' },
  COMPLIANCE: { label: 'Compliance', color: 'emerald' },
};

export const getFeatureByKey = (key) => features.find((f) => f.key === key);
