const statusOptions = ['queued', 'running', 'active', 'completed', 'failed', 'review', 'ready'];
const priorityOptions = ['critical', 'high', 'medium', 'low'];
const riskOptions = ['low', 'medium', 'high', 'critical'];
const booleanOptions = ['true', 'false'];

export const features = [
  {
    key: 'cases',
    title: 'Case Management',
    apiEndpoint: '/cases',
    icon: 'Briefcase',
    description: 'Manage litigation cases and matters',
    color: 'blue',
    group: 'CORE',
    columns: [
      { key: 'case_name', label: 'Case Name' },
      { key: 'case_number', label: 'Case #' },
      { key: 'client_name', label: 'Client' },
      { key: 'matter_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'priority', label: 'Priority' },
    ],
    formFields: [
      { key: 'case_name', label: 'Case Name', type: 'text', required: true },
      { key: 'case_number', label: 'Case Number', type: 'text', required: true },
      { key: 'client_name', label: 'Client Name', type: 'text', required: true },
      { key: 'matter_type', label: 'Matter Type', type: 'select', options: ['litigation', 'investigation', 'regulatory', 'compliance'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'pending', 'closed', 'archived'] },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'lead_attorney', label: 'Lead Attorney', type: 'text' },
      { key: 'date_filed', label: 'Date Filed', type: 'date' },
      { key: 'court_jurisdiction', label: 'Court/Jurisdiction', type: 'text' },
      { key: 'opposing_counsel', label: 'Opposing Counsel', type: 'text' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['high', 'medium', 'low'] },
    ],
  },
  {
    key: 'documents',
    title: 'Document Review',
    apiEndpoint: '/documents',
    icon: 'FileText',
    description: 'Review and classify case documents',
    color: 'indigo',
    group: 'CORE',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'file_type', label: 'Type' },
      { key: 'custodian', label: 'Custodian' },
      { key: 'review_status', label: 'Review Status' },
      { key: 'bates_number', label: 'Bates #' },
      { key: 'date_collected', label: 'Collected' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'file_type', label: 'File Type', type: 'select', options: ['pdf', 'docx', 'xlsx', 'eml', 'pptx', 'txt', 'csv', 'html'] },
      { key: 'file_size_mb', label: 'File Size (MB)', type: 'number' },
      { key: 'custodian', label: 'Custodian', type: 'text' },
      { key: 'source', label: 'Source', type: 'text' },
      { key: 'review_status', label: 'Review Status', type: 'select', options: ['pending', 'relevant', 'not_relevant', 'privileged', 'hot'] },
      { key: 'content_preview', label: 'Content Preview', type: 'textarea' },
      { key: 'date_collected', label: 'Date Collected', type: 'date' },
      { key: 'bates_number', label: 'Bates Number', type: 'text' },
      { key: 'hash_value', label: 'Hash Value', type: 'text' },
    ],
  },
  {
    key: 'legal-holds',
    title: 'Legal Holds',
    apiEndpoint: '/legal-holds',
    icon: 'Shield',
    description: 'Manage preservation and legal hold notices',
    color: 'red',
    group: 'MANAGEMENT',
    columns: [
      { key: 'hold_name', label: 'Hold Name' },
      { key: 'hold_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'custodian_count', label: 'Custodians' },
      { key: 'issued_date', label: 'Issued Date' },
      { key: 'notification_sent', label: 'Notified' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'hold_name', label: 'Hold Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'released', 'pending', 'expired'] },
      { key: 'custodian_count', label: 'Custodian Count', type: 'number' },
      { key: 'issued_by', label: 'Issued By', type: 'text' },
      { key: 'issued_date', label: 'Issued Date', type: 'date' },
      { key: 'release_date', label: 'Release Date', type: 'date' },
      { key: 'hold_type', label: 'Hold Type', type: 'select', options: ['litigation', 'regulatory', 'investigation'] },
      { key: 'notification_sent', label: 'Notification Sent', type: 'select', options: ['true', 'false'] },
    ],
  },
  {
    key: 'custodians',
    title: 'Custodian Management',
    apiEndpoint: '/custodians',
    icon: 'Users',
    description: 'Manage data custodians and their obligations',
    color: 'green',
    group: 'MANAGEMENT',
    columns: [
      { key: 'full_name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'department', label: 'Department' },
      { key: 'company', label: 'Company' },
      { key: 'status', label: 'Status' },
      { key: 'hold_status', label: 'Hold Status' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'full_name', label: 'Full Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'department', label: 'Department', type: 'text' },
      { key: 'title', label: 'Job Title', type: 'text' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'terminated'] },
      { key: 'data_sources', label: 'Data Sources', type: 'textarea' },
      { key: 'hold_status', label: 'Hold Status', type: 'select', options: ['on_hold', 'released', 'pending'] },
      { key: 'interview_date', label: 'Interview Date', type: 'date' },
    ],
  },
  {
    key: 'collections',
    title: 'Collections',
    apiEndpoint: '/collections',
    icon: 'FolderOpen',
    description: 'Manage data collection activities',
    color: 'yellow',
    group: 'MANAGEMENT',
    columns: [
      { key: 'collection_name', label: 'Collection Name' },
      { key: 'source_type', label: 'Source Type' },
      { key: 'custodian', label: 'Custodian' },
      { key: 'status', label: 'Status' },
      { key: 'total_items', label: 'Items' },
      { key: 'collection_date', label: 'Collected' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'collection_name', label: 'Collection Name', type: 'text', required: true },
      { key: 'source_type', label: 'Source Type', type: 'select', options: ['email', 'file_share', 'cloud', 'database', 'mobile', 'chat'] },
      { key: 'custodian', label: 'Custodian', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed', 'failed'] },
      { key: 'total_items', label: 'Total Items', type: 'number' },
      { key: 'total_size_gb', label: 'Total Size (GB)', type: 'number' },
      { key: 'collected_by', label: 'Collected By', type: 'text' },
      { key: 'collection_date', label: 'Collection Date', type: 'date' },
      { key: 'verification_status', label: 'Verification Status', type: 'text' },
    ],
  },
  {
    key: 'processing-jobs',
    title: 'Processing Jobs',
    apiEndpoint: '/processing-jobs',
    icon: 'Cpu',
    description: 'Track document processing and deduplication',
    color: 'orange',
    group: 'PROCESSING',
    columns: [
      { key: 'job_name', label: 'Job Name' },
      { key: 'processing_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'total_documents', label: 'Total Docs' },
      { key: 'processed_count', label: 'Processed' },
      { key: 'error_count', label: 'Errors' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'job_name', label: 'Job Name', type: 'text', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['queued', 'processing', 'completed', 'failed', 'paused'] },
      { key: 'total_documents', label: 'Total Documents', type: 'number' },
      { key: 'processed_count', label: 'Processed Count', type: 'number' },
      { key: 'duplicate_count', label: 'Duplicate Count', type: 'number' },
      { key: 'error_count', label: 'Error Count', type: 'number' },
      { key: 'processing_type', label: 'Processing Type', type: 'select', options: ['dedup', 'ocr', 'extraction', 'normalization'] },
    ],
  },
  {
    key: 'review-sets',
    title: 'Review Sets',
    apiEndpoint: '/review-sets',
    icon: 'Eye',
    description: 'Organize documents for review workflows',
    color: 'purple',
    group: 'PROCESSING',
    columns: [
      { key: 'set_name', label: 'Review Set' },
      { key: 'reviewer', label: 'Reviewer' },
      { key: 'status', label: 'Status' },
      { key: 'total_documents', label: 'Total' },
      { key: 'reviewed_count', label: 'Reviewed' },
      { key: 'priority', label: 'Priority' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'set_name', label: 'Set Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'total_documents', label: 'Total Documents', type: 'number' },
      { key: 'reviewed_count', label: 'Reviewed Count', type: 'number' },
      { key: 'relevant_count', label: 'Relevant Count', type: 'number' },
      { key: 'privileged_count', label: 'Privileged Count', type: 'number' },
      { key: 'reviewer', label: 'Reviewer', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'completed', 'paused'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['high', 'medium', 'low'] },
    ],
  },
  {
    key: 'productions',
    title: 'Productions',
    apiEndpoint: '/productions',
    icon: 'Package',
    description: 'Manage document production sets',
    color: 'teal',
    group: 'PROCESSING',
    columns: [
      { key: 'production_name', label: 'Production Name' },
      { key: 'bates_prefix', label: 'Bates Prefix' },
      { key: 'status', label: 'Status' },
      { key: 'format', label: 'Format' },
      { key: 'total_documents', label: 'Documents' },
      { key: 'confidentiality_level', label: 'Confidentiality' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'production_name', label: 'Production Name', type: 'text', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed', 'delivered'] },
      { key: 'format', label: 'Format', type: 'select', options: ['native', 'tiff', 'pdf'] },
      { key: 'total_documents', label: 'Total Documents', type: 'number' },
      { key: 'bates_prefix', label: 'Bates Prefix', type: 'text' },
      { key: 'bates_start', label: 'Bates Start', type: 'number' },
      { key: 'bates_end', label: 'Bates End', type: 'number' },
      { key: 'recipient', label: 'Recipient', type: 'text' },
      { key: 'delivery_date', label: 'Delivery Date', type: 'date' },
      { key: 'confidentiality_level', label: 'Confidentiality', type: 'select', options: ['confidential', 'highly_confidential', 'attorneys_eyes_only', 'public'] },
    ],
  },
  {
    key: 'search-queries',
    title: 'Search & Analytics',
    apiEndpoint: '/search-queries',
    icon: 'Search',
    description: 'Run and manage document search queries',
    color: 'cyan',
    group: 'ANALYSIS',
    columns: [
      { key: 'query_name', label: 'Query Name' },
      { key: 'query_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'results_count', label: 'Results' },
      { key: 'created_by', label: 'Created By' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'query_name', label: 'Query Name', type: 'text', required: true },
      { key: 'search_terms', label: 'Search Terms', type: 'textarea', required: true },
      { key: 'query_type', label: 'Query Type', type: 'select', options: ['keyword', 'boolean', 'concept', 'regex', 'proximity'] },
      { key: 'results_count', label: 'Results Count', type: 'number' },
      { key: 'created_by', label: 'Created By', type: 'text' },
      { key: 'date_range_start', label: 'Date Range Start', type: 'date' },
      { key: 'date_range_end', label: 'Date Range End', type: 'date' },
      { key: 'file_types_filter', label: 'File Types Filter', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['saved', 'executed', 'archived'] },
    ],
  },
  {
    key: 'predictive-coding',
    title: 'Predictive Coding',
    apiEndpoint: '/predictive-coding',
    icon: 'Brain',
    description: 'AI-powered document classification models',
    color: 'pink',
    group: 'ANALYSIS',
    columns: [
      { key: 'model_name', label: 'Model Name' },
      { key: 'algorithm', label: 'Algorithm' },
      { key: 'status', label: 'Status' },
      { key: 'accuracy', label: 'Accuracy' },
      { key: 'coded_docs', label: 'Coded Docs' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'model_name', label: 'Model Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['training', 'active', 'completed', 'archived'] },
      { key: 'accuracy', label: 'Accuracy', type: 'number' },
      { key: 'precision_score', label: 'Precision', type: 'number' },
      { key: 'recall_score', label: 'Recall', type: 'number' },
      { key: 'f1_score', label: 'F1 Score', type: 'number' },
      { key: 'training_docs', label: 'Training Docs', type: 'number' },
      { key: 'coded_docs', label: 'Coded Docs', type: 'number' },
      { key: 'algorithm', label: 'Algorithm', type: 'select', options: ['logistic_regression', 'svm', 'random_forest', 'neural_network', 'transformer'] },
    ],
  },
  {
    key: 'key-terms',
    title: 'Key Terms Analysis',
    apiEndpoint: '/key-terms',
    icon: 'Hash',
    description: 'Analyze key search terms and patterns',
    color: 'lime',
    group: 'ANALYSIS',
    columns: [
      { key: 'term', label: 'Term' },
      { key: 'category', label: 'Category' },
      { key: 'frequency', label: 'Frequency' },
      { key: 'relevance_score', label: 'Relevance' },
      { key: 'document_count', label: 'Documents' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'term', label: 'Term', type: 'text', required: true },
      { key: 'frequency', label: 'Frequency', type: 'number' },
      { key: 'relevance_score', label: 'Relevance Score', type: 'number' },
      { key: 'category', label: 'Category', type: 'select', options: ['person', 'organization', 'location', 'date', 'concept', 'financial'] },
      { key: 'context_snippet', label: 'Context Snippet', type: 'textarea' },
      { key: 'first_occurrence', label: 'First Occurrence', type: 'date' },
      { key: 'last_occurrence', label: 'Last Occurrence', type: 'date' },
      { key: 'document_count', label: 'Document Count', type: 'number' },
    ],
  },
  {
    key: 'timeline-events',
    title: 'Timeline Analysis',
    apiEndpoint: '/timeline-events',
    icon: 'Clock',
    description: 'Build and analyze case timelines',
    color: 'amber',
    group: 'INTELLIGENCE',
    columns: [
      { key: 'event_title', label: 'Event' },
      { key: 'event_date', label: 'Date' },
      { key: 'category', label: 'Category' },
      { key: 'significance', label: 'Significance' },
      { key: 'ai_generated', label: 'AI Generated' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'event_title', label: 'Event Title', type: 'text', required: true },
      { key: 'event_date', label: 'Event Date', type: 'date', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'category', label: 'Category', type: 'select', options: ['communication', 'filing', 'meeting', 'transaction', 'incident', 'discovery'] },
      { key: 'source_document', label: 'Source Document', type: 'text' },
      { key: 'participants', label: 'Participants', type: 'textarea' },
      { key: 'significance', label: 'Significance', type: 'select', options: ['high', 'medium', 'low'] },
      { key: 'ai_generated', label: 'AI Generated', type: 'select', options: ['true', 'false'] },
    ],
  },
  {
    key: 'email-threads',
    title: 'Email Threading',
    apiEndpoint: '/email-threads',
    icon: 'Mail',
    description: 'Analyze and organize email conversations',
    color: 'sky',
    group: 'INTELLIGENCE',
    columns: [
      { key: 'thread_subject', label: 'Subject' },
      { key: 'participant_count', label: 'Participants' },
      { key: 'message_count', label: 'Messages' },
      { key: 'sentiment', label: 'Sentiment' },
      { key: 'relevance_score', label: 'Relevance' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'thread_subject', label: 'Thread Subject', type: 'text', required: true },
      { key: 'participant_count', label: 'Participant Count', type: 'number' },
      { key: 'message_count', label: 'Message Count', type: 'number' },
      { key: 'date_range', label: 'Date Range', type: 'text' },
      { key: 'key_participants', label: 'Key Participants', type: 'textarea' },
      { key: 'has_attachments', label: 'Has Attachments', type: 'select', options: ['true', 'false'] },
      { key: 'sentiment', label: 'Sentiment', type: 'text' },
      { key: 'relevance_score', label: 'Relevance Score', type: 'number' },
      { key: 'thread_summary', label: 'Thread Summary', type: 'textarea' },
    ],
  },
  {
    key: 'anomaly-alerts',
    title: 'Anomaly Detection',
    apiEndpoint: '/anomaly-alerts',
    icon: 'AlertTriangle',
    description: 'Monitor and investigate data anomalies',
    color: 'rose',
    group: 'INTELLIGENCE',
    columns: [
      { key: 'alert_title', label: 'Alert' },
      { key: 'severity', label: 'Severity' },
      { key: 'alert_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'detected_date', label: 'Detected' },
      { key: 'ai_confidence', label: 'Confidence' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'alert_title', label: 'Alert Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'severity', label: 'Severity', type: 'select', options: ['critical', 'high', 'medium', 'low'] },
      { key: 'alert_type', label: 'Alert Type', type: 'select', options: ['data_gap', 'spike', 'pattern', 'unusual_access', 'deletion'] },
      { key: 'detected_date', label: 'Detected Date', type: 'date' },
      { key: 'affected_custodian', label: 'Affected Custodian', type: 'text' },
      { key: 'affected_date_range', label: 'Affected Date Range', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['new', 'investigating', 'resolved', 'dismissed'] },
      { key: 'ai_confidence', label: 'AI Confidence', type: 'number' },
    ],
  },
  {
    key: 'privilege-logs',
    title: 'Privilege Review',
    apiEndpoint: '/privilege-logs',
    icon: 'Lock',
    description: 'Track attorney-client privilege claims',
    color: 'violet',
    group: 'COMPLIANCE',
    columns: [
      { key: 'document_title', label: 'Document' },
      { key: 'bates_number', label: 'Bates #' },
      { key: 'privilege_type', label: 'Privilege Type' },
      { key: 'status', label: 'Status' },
      { key: 'reviewer', label: 'Reviewer' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'document_title', label: 'Document Title', type: 'text', required: true },
      { key: 'bates_number', label: 'Bates Number', type: 'text' },
      { key: 'privilege_type', label: 'Privilege Type', type: 'select', options: ['attorney_client', 'work_product', 'joint_defense', 'common_interest'] },
      { key: 'basis', label: 'Basis', type: 'textarea' },
      { key: 'author', label: 'Author', type: 'text' },
      { key: 'recipients', label: 'Recipients', type: 'textarea' },
      { key: 'date_of_communication', label: 'Date of Communication', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['logged', 'challenged', 'upheld', 'waived'] },
      { key: 'reviewer', label: 'Reviewer', type: 'text' },
    ],
  },
  {
    key: 'compliance-rules',
    title: 'Compliance Monitoring',
    apiEndpoint: '/compliance-rules',
    icon: 'CheckSquare',
    description: 'Define and enforce compliance policies',
    color: 'emerald',
    group: 'COMPLIANCE',
    columns: [
      { key: 'rule_name', label: 'Rule Name' },
      { key: 'regulation', label: 'Regulation' },
      { key: 'severity', label: 'Severity' },
      { key: 'status', label: 'Status' },
      { key: 'violations_count', label: 'Violations' },
      { key: 'automated', label: 'Automated' },
    ],
    formFields: [
      { key: 'rule_name', label: 'Rule Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'regulation', label: 'Regulation', type: 'select', options: ['gdpr', 'hipaa', 'sox', 'fcpa', 'ccpa', 'sec', 'frcp'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'under_review'] },
      { key: 'violations_count', label: 'Violations Count', type: 'number' },
      { key: 'affected_cases', label: 'Affected Cases', type: 'number' },
      { key: 'severity', label: 'Severity', type: 'select', options: ['critical', 'high', 'medium', 'low'] },
      { key: 'automated', label: 'Automated', type: 'select', options: ['true', 'false'] },
      { key: 'remediation_steps', label: 'Remediation Steps', type: 'textarea' },
    ],
  },
  {
    key: 'data-sources',
    title: 'Data Sources',
    apiEndpoint: '/data-sources',
    icon: 'Database',
    description: 'Manage connected data repositories',
    color: 'slate',
    group: 'COMPLIANCE',
    columns: [
      { key: 'source_name', label: 'Source Name' },
      { key: 'source_type', label: 'Type' },
      { key: 'connection_status', label: 'Connection' },
      { key: 'total_items', label: 'Items' },
      { key: 'last_synced', label: 'Last Synced' },
      { key: 'collection_priority', label: 'Priority' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number', required: true },
      { key: 'source_name', label: 'Source Name', type: 'text', required: true },
      { key: 'source_type', label: 'Source Type', type: 'select', options: ['exchange', 'sharepoint', 'onedrive', 'slack', 'teams', 'salesforce', 'box', 'google_workspace', 'local_server'] },
      { key: 'connection_status', label: 'Connection Status', type: 'select', options: ['connected', 'disconnected', 'error', 'pending'] },
      { key: 'custodian', label: 'Custodian', type: 'text' },
      { key: 'total_items', label: 'Total Items', type: 'number' },
      { key: 'total_size_gb', label: 'Total Size (GB)', type: 'number' },
      { key: 'credentials_stored', label: 'Credentials Stored', type: 'select', options: ['true', 'false'] },
      { key: 'collection_priority', label: 'Collection Priority', type: 'select', options: ['high', 'medium', 'low'] },
    ],
  },
  {
    key: 'file-viewer',
    title: 'File Viewer',
    apiEndpoint: '/file-viewer',
    icon: 'FileText',
    description: 'Preview documents, OCR status, extracted pages, and redaction overlays',
    color: 'blue',
    group: 'ENTERPRISE',
    actions: [{ key: 'extract-preview', label: 'Extract Preview' }],
    columns: [
      { key: 'viewer_name', label: 'Viewer Session' },
      { key: 'file_type', label: 'Type' },
      { key: 'preview_status', label: 'Preview' },
      { key: 'ocr_status', label: 'OCR' },
      { key: 'extracted_pages', label: 'Pages' },
      { key: 'last_viewed_by', label: 'Last Viewed By' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number' },
      { key: 'document_id', label: 'Document ID', type: 'number' },
      { key: 'viewer_name', label: 'Viewer Session', type: 'text', required: true },
      { key: 'file_type', label: 'File Type', type: 'select', options: ['pdf', 'docx', 'xlsx', 'eml', 'pptx', 'txt', 'csv'] },
      { key: 'preview_status', label: 'Preview Status', type: 'select', options: ['ready', 'rendering', 'failed', 'queued'] },
      { key: 'ocr_status', label: 'OCR Status', type: 'select', options: ['complete', 'pending', 'failed', 'not_required'] },
      { key: 'extracted_pages', label: 'Extracted Pages', type: 'number' },
      { key: 'redaction_overlay', label: 'Redaction Overlay', type: 'select', options: booleanOptions },
      { key: 'last_viewed_by', label: 'Last Viewed By', type: 'text' },
      { key: 'last_viewed_at', label: 'Last Viewed At', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'ingestion-pipelines',
    title: 'Ingestion Pipelines',
    apiEndpoint: '/ingestion-pipelines',
    icon: 'Cpu',
    description: 'Track collection ingestion, dedupe, OCR, indexing, and exceptions',
    color: 'orange',
    group: 'ENTERPRISE',
    actions: [{ key: 'run-ingestion', label: 'Run Ingestion' }],
    columns: [
      { key: 'pipeline_name', label: 'Pipeline' },
      { key: 'source_system', label: 'Source' },
      { key: 'stage', label: 'Stage' },
      { key: 'status', label: 'Status' },
      { key: 'items_ingested', label: 'Ingested' },
      { key: 'items_failed', label: 'Failed' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number' },
      { key: 'pipeline_name', label: 'Pipeline Name', type: 'text', required: true },
      { key: 'source_system', label: 'Source System', type: 'select', options: ['Exchange Online', 'Slack Enterprise', 'SharePoint', 'Box', 'Google Workspace', 'Local Server'] },
      { key: 'stage', label: 'Stage', type: 'select', options: ['collect', 'dedupe', 'ocr', 'index', 'qc'] },
      { key: 'status', label: 'Status', type: 'select', options: statusOptions },
      { key: 'items_ingested', label: 'Items Ingested', type: 'number' },
      { key: 'items_failed', label: 'Items Failed', type: 'number' },
      { key: 'dedupe_rate', label: 'Dedupe Rate', type: 'number' },
      { key: 'ocr_complete', label: 'OCR Complete', type: 'select', options: booleanOptions },
      { key: 'started_at', label: 'Started At', type: 'date' },
      { key: 'completed_at', label: 'Completed At', type: 'date' },
      { key: 'owner', label: 'Owner', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'connector-syncs',
    title: 'Connector Syncs',
    apiEndpoint: '/connector-syncs',
    icon: 'Database',
    description: 'Monitor source connector health, auth status, sync counts, and failures',
    color: 'slate',
    group: 'ENTERPRISE',
    actions: [{ key: 'run-sync', label: 'Run Sync' }],
    columns: [
      { key: 'connector_name', label: 'Connector' },
      { key: 'provider', label: 'Provider' },
      { key: 'sync_status', label: 'Sync Status' },
      { key: 'auth_status', label: 'Auth' },
      { key: 'records_synced', label: 'Synced' },
      { key: 'risk_level', label: 'Risk' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number' },
      { key: 'connector_name', label: 'Connector Name', type: 'text', required: true },
      { key: 'provider', label: 'Provider', type: 'select', options: ['Microsoft 365', 'Google Vault', 'Slack', 'Salesforce', 'SAP', 'Box'] },
      { key: 'sync_status', label: 'Sync Status', type: 'select', options: ['healthy', 'warning', 'failed', 'scheduled'] },
      { key: 'last_sync_at', label: 'Last Sync At', type: 'date' },
      { key: 'next_sync_at', label: 'Next Sync At', type: 'date' },
      { key: 'records_synced', label: 'Records Synced', type: 'number' },
      { key: 'records_failed', label: 'Records Failed', type: 'number' },
      { key: 'auth_status', label: 'Auth Status', type: 'select', options: ['valid', 'expires_soon', 'reauthorize'] },
      { key: 'owner', label: 'Owner', type: 'text' },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: riskOptions },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'review-assignments',
    title: 'Review Assignments',
    apiEndpoint: '/review-assignments',
    icon: 'Eye',
    description: 'Assign reviewer batches, QC requirements, deadlines, and coding instructions',
    color: 'purple',
    group: 'ENTERPRISE',
    actions: [{ key: 'run-qc', label: 'Run QC' }],
    columns: [
      { key: 'assignment_name', label: 'Assignment' },
      { key: 'reviewer', label: 'Reviewer' },
      { key: 'batch_size', label: 'Batch' },
      { key: 'completed_count', label: 'Completed' },
      { key: 'priority', label: 'Priority' },
      { key: 'status', label: 'Status' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number' },
      { key: 'review_set_id', label: 'Review Set ID', type: 'number' },
      { key: 'assignment_name', label: 'Assignment Name', type: 'text', required: true },
      { key: 'reviewer', label: 'Reviewer', type: 'text' },
      { key: 'batch_size', label: 'Batch Size', type: 'number' },
      { key: 'completed_count', label: 'Completed Count', type: 'number' },
      { key: 'qc_required', label: 'QC Required', type: 'select', options: booleanOptions },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'priority', label: 'Priority', type: 'select', options: priorityOptions },
      { key: 'status', label: 'Status', type: 'select', options: statusOptions },
      { key: 'instructions', label: 'Instructions', type: 'textarea' },
    ],
  },
  {
    key: 'redaction-jobs',
    title: 'Redaction Jobs',
    apiEndpoint: '/redaction-jobs',
    icon: 'Sparkles',
    description: 'Manage PII, PHI, privilege, and trade-secret redaction workflows',
    color: 'rose',
    group: 'ENTERPRISE',
    actions: [{ key: 'apply-redactions', label: 'Apply Redactions' }],
    columns: [
      { key: 'redaction_name', label: 'Redaction Job' },
      { key: 'redaction_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'items_detected', label: 'Detected' },
      { key: 'items_applied', label: 'Applied' },
      { key: 'confidence_score', label: 'Confidence' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number' },
      { key: 'document_id', label: 'Document ID', type: 'number' },
      { key: 'redaction_name', label: 'Redaction Name', type: 'text', required: true },
      { key: 'redaction_type', label: 'Redaction Type', type: 'select', options: ['PII', 'PHI', 'privilege', 'trade_secret', 'financial'] },
      { key: 'status', label: 'Status', type: 'select', options: statusOptions },
      { key: 'items_detected', label: 'Items Detected', type: 'number' },
      { key: 'items_applied', label: 'Items Applied', type: 'number' },
      { key: 'reviewer', label: 'Reviewer', type: 'text' },
      { key: 'confidence_score', label: 'Confidence Score', type: 'number' },
      { key: 'completed_at', label: 'Completed At', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'production-packages',
    title: 'Production Packages',
    apiEndpoint: '/production-packages',
    icon: 'Package',
    description: 'Track production packages, Bates ranges, load files, QC, and delivery',
    color: 'teal',
    group: 'ENTERPRISE',
    actions: [{ key: 'validate-production', label: 'Validate Production' }],
    columns: [
      { key: 'package_name', label: 'Package' },
      { key: 'package_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'document_count', label: 'Docs' },
      { key: 'load_file_status', label: 'Load File' },
      { key: 'qc_status', label: 'QC' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number' },
      { key: 'production_id', label: 'Production ID', type: 'number' },
      { key: 'package_name', label: 'Package Name', type: 'text', required: true },
      { key: 'package_type', label: 'Package Type', type: 'select', options: ['rolling', 'regulatory', 'privilege', 'expert', 'final'] },
      { key: 'status', label: 'Status', type: 'select', options: statusOptions },
      { key: 'document_count', label: 'Document Count', type: 'number' },
      { key: 'bates_start', label: 'Bates Start', type: 'number' },
      { key: 'bates_end', label: 'Bates End', type: 'number' },
      { key: 'load_file_status', label: 'Load File Status', type: 'select', options: ['ready', 'building', 'failed', 'validated'] },
      { key: 'qc_status', label: 'QC Status', type: 'select', options: ['pending', 'passed', 'exceptions'] },
      { key: 'delivered_at', label: 'Delivered At', type: 'date' },
      { key: 'recipient', label: 'Recipient', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'notification-delivery',
    title: 'Notification Delivery',
    apiEndpoint: '/notification-delivery',
    icon: 'Mail',
    description: 'Track email, Slack, SMS, and portal notifications with acknowledgement status',
    color: 'sky',
    group: 'ENTERPRISE',
    actions: [{ key: 'send-test', label: 'Send Test' }],
    columns: [
      { key: 'notification_name', label: 'Notification' },
      { key: 'channel', label: 'Channel' },
      { key: 'recipient', label: 'Recipient' },
      { key: 'delivery_status', label: 'Status' },
      { key: 'retry_count', label: 'Retries' },
      { key: 'priority', label: 'Priority' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number' },
      { key: 'notification_name', label: 'Notification Name', type: 'text', required: true },
      { key: 'channel', label: 'Channel', type: 'select', options: ['email', 'slack', 'sms', 'portal'] },
      { key: 'recipient', label: 'Recipient', type: 'text' },
      { key: 'template_name', label: 'Template Name', type: 'select', options: ['legal_hold_notice', 'review_due', 'production_qc', 'connector_failure'] },
      { key: 'delivery_status', label: 'Delivery Status', type: 'select', options: ['sent', 'acknowledged', 'failed', 'queued'] },
      { key: 'sent_at', label: 'Sent At', type: 'date' },
      { key: 'acknowledged_at', label: 'Acknowledged At', type: 'date' },
      { key: 'retry_count', label: 'Retry Count', type: 'number' },
      { key: 'priority', label: 'Priority', type: 'select', options: priorityOptions },
      { key: 'message_summary', label: 'Message Summary', type: 'textarea' },
    ],
  },
  {
    key: 'rbac-permissions',
    title: 'RBAC Permissions',
    apiEndpoint: '/rbac-permissions',
    icon: 'Lock',
    description: 'Review role permissions, resource access, enforcement, and access risk',
    color: 'violet',
    group: 'ENTERPRISE',
    actions: [{ key: 'enforce-permission', label: 'Enforce Permission' }],
    columns: [
      { key: 'permission_name', label: 'Permission' },
      { key: 'role_name', label: 'Role' },
      { key: 'resource_area', label: 'Resource' },
      { key: 'access_level', label: 'Access' },
      { key: 'enforced', label: 'Enforced' },
      { key: 'risk_level', label: 'Risk' },
    ],
    formFields: [
      { key: 'permission_name', label: 'Permission Name', type: 'text', required: true },
      { key: 'role_name', label: 'Role Name', type: 'select', options: ['Admin', 'Attorney', 'Reviewer', 'Client', 'Forensics'] },
      { key: 'resource_area', label: 'Resource Area', type: 'select', options: ['cases', 'documents', 'productions', 'ai_tools', 'admin'] },
      { key: 'access_level', label: 'Access Level', type: 'select', options: ['read', 'write', 'approve', 'export', 'admin'] },
      { key: 'enforced', label: 'Enforced', type: 'select', options: booleanOptions },
      { key: 'last_reviewed_at', label: 'Last Reviewed At', type: 'date' },
      { key: 'reviewer', label: 'Reviewer', type: 'text' },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: riskOptions },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'audit-binders',
    title: 'Audit Binders',
    apiEndpoint: '/audit-binders',
    icon: 'CheckSquare',
    description: 'Build defensibility binders for preservation, collection, review, production, and AI governance',
    color: 'emerald',
    group: 'ENTERPRISE',
    actions: [{ key: 'generate-pdf', label: 'Generate PDF' }],
    columns: [
      { key: 'binder_name', label: 'Binder' },
      { key: 'binder_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'evidence_count', label: 'Evidence' },
      { key: 'control_count', label: 'Controls' },
      { key: 'signoff_status', label: 'Signoff' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number' },
      { key: 'binder_name', label: 'Binder Name', type: 'text', required: true },
      { key: 'binder_type', label: 'Binder Type', type: 'select', options: ['preservation', 'collection', 'review', 'production', 'ai_governance'] },
      { key: 'status', label: 'Status', type: 'select', options: statusOptions },
      { key: 'evidence_count', label: 'Evidence Count', type: 'number' },
      { key: 'control_count', label: 'Control Count', type: 'number' },
      { key: 'export_format', label: 'Export Format', type: 'select', options: ['pdf', 'csv', 'json', 'zip'] },
      { key: 'generated_by', label: 'Generated By', type: 'text' },
      { key: 'generated_at', label: 'Generated At', type: 'date' },
      { key: 'signoff_status', label: 'Signoff Status', type: 'select', options: ['pending', 'approved', 'needs_review'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'background-jobs',
    title: 'Background Jobs',
    apiEndpoint: '/background-jobs',
    icon: 'Clock',
    description: 'Monitor scheduled syncs, OCR, notifications, exports, retries, and AI jobs',
    color: 'amber',
    group: 'ENTERPRISE',
    actions: [{ key: 'run-now', label: 'Run Now' }],
    columns: [
      { key: 'job_name', label: 'Job' },
      { key: 'job_type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'scheduled_at', label: 'Scheduled' },
      { key: 'retry_count', label: 'Retries' },
      { key: 'owner', label: 'Owner' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number' },
      { key: 'job_name', label: 'Job Name', type: 'text', required: true },
      { key: 'job_type', label: 'Job Type', type: 'select', options: ['sync', 'ocr', 'notification', 'export', 'ai_review'] },
      { key: 'status', label: 'Status', type: 'select', options: statusOptions },
      { key: 'scheduled_at', label: 'Scheduled At', type: 'date' },
      { key: 'started_at', label: 'Started At', type: 'date' },
      { key: 'finished_at', label: 'Finished At', type: 'date' },
      { key: 'retry_count', label: 'Retry Count', type: 'number' },
      { key: 'last_error', label: 'Last Error', type: 'textarea' },
      { key: 'owner', label: 'Owner', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'ai-governance',
    title: 'AI Governance',
    apiEndpoint: '/ai-governance',
    icon: 'Brain',
    description: 'Govern models, prompts, fallbacks, cost, approval, risk, and reviewer signoff',
    color: 'pink',
    group: 'ENTERPRISE',
    actions: [{ key: 'approve-governance', label: 'Approve' }],
    columns: [
      { key: 'governance_name', label: 'Governance Record' },
      { key: 'model_name', label: 'Model' },
      { key: 'prompt_version', label: 'Prompt' },
      { key: 'approval_status', label: 'Approval' },
      { key: 'cost_usd', label: 'Cost' },
      { key: 'risk_level', label: 'Risk' },
    ],
    formFields: [
      { key: 'case_id', label: 'Case ID', type: 'number' },
      { key: 'governance_name', label: 'Governance Name', type: 'text', required: true },
      { key: 'model_name', label: 'Model Name', type: 'select', options: ['anthropic/claude-3-5-sonnet', 'openai/gpt-4.1', 'google/gemini-pro', 'meta-llama/llama-3.1'] },
      { key: 'prompt_version', label: 'Prompt Version', type: 'text' },
      { key: 'approval_status', label: 'Approval Status', type: 'select', options: ['approved', 'pending', 'rejected', 'needs_review'] },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
      { key: 'approved_at', label: 'Approved At', type: 'date' },
      { key: 'cost_usd', label: 'Cost USD', type: 'number' },
      { key: 'fallback_model', label: 'Fallback Model', type: 'select', options: ['anthropic/claude-haiku', 'openai/gpt-4o-mini', 'local-rules-engine'] },
      { key: 'reviewer_signoff', label: 'Reviewer Signoff', type: 'select', options: booleanOptions },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: riskOptions },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
];

export const featureGroups = {
  CORE: { label: 'Core', color: 'blue' },
  MANAGEMENT: { label: 'Management', color: 'green' },
  PROCESSING: { label: 'Processing', color: 'orange' },
  ANALYSIS: { label: 'Analysis', color: 'cyan' },
  INTELLIGENCE: { label: 'Intelligence', color: 'amber' },
  COMPLIANCE: { label: 'Compliance', color: 'emerald' },
  ENTERPRISE: { label: 'Enterprise Ops', color: 'purple' },
};

export const getFeatureByKey = (key) => features.find((f) => f.key === key);
